### ISSUE TITLE
I'm getting an error

### ISSUE THREAD

**Issue by srktnc** [yuki-koyama/bigger#23]
when i try to run i get two shader errors;

`Error D3DCompile failed 0x80004005 (100,26-67): error X3020: type mismatch`

`Error D3DCompile failed 0x80004005 (130.21): error X3037: constructors only defined for numeric base types `

**Comment by mrlinds** [comment]
Just in case someone else gets this error, I think I fixed it by specifying BGFX_OPENGL_VERSION on the cmake window list of settings, and regenerating
