### ISSUE TITLE
how to implement the Floating drag panel ??

### ISSUE THREAD

**Issue by Corezcy** [yuki-koyama/bigger#6]
as the title ,could you please tell me how to make a ui like that ? or where is the relevant code?
![image](https://user-images.githubusercontent.com/33271784/99550951-3d2d3a80-29f6-11eb-9957-591c41bc2e22.png)

**Comment by yuki-koyama** [comment]
This part:
```cpp
    // Display ImGui components
    ImGui::Begin("Config");
    {
        ImGui::Text("frame: %d", m_frame);
        ImGui::Text("time: %.2f", m_time);
        ImGui::Text("fps: %.2f", 1.0f / m_last_dt);
        ImGui::Separator();
        ImGui::SliderFloat3("camera.position", glm::value_ptr(getCamera().m_position), - 10.0f, 10.0f);
        ImGui::SliderFloat("camera.fov", &(getCamera().m_fov), 10.0f, 120.0f);
        ImGui::Separator();
        m_mesh_material->drawImgui();
    }
    ImGui::End();
```
https://github.com/yuki-koyama/bigger/blob/bfbc728e43db0c1e37b47becd29f8992468efc01/examples/mesh/main.cpp#L102-L114

**Comment by Corezcy** [comment]
> This part:
> https://github.com/yuki-koyama/bigger/blob/bfbc728e43db0c1e37b47becd29f8992468efc01/examples/mesh/main.cpp#L102-L114

thank you very much !!
